"""cambio nombre propiedades

Revision ID: 4af0cfe04df4
Revises: 846231566141
Create Date: 2023-12-28 17:36:11.221033

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '4af0cfe04df4'
down_revision = '846231566141'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usuarios', schema=None) as batch_op:
        batch_op.add_column(sa.Column('es_prestador', sa.Boolean(), nullable=False))
        batch_op.add_column(sa.Column('foto_perfil', sa.String(length=255), nullable=True))
        batch_op.drop_column('esPrestador')
        batch_op.drop_column('fotoPerfil')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usuarios', schema=None) as batch_op:
        batch_op.add_column(sa.Column('fotoPerfil', mysql.VARCHAR(length=255), nullable=True))
        batch_op.add_column(sa.Column('esPrestador', mysql.TINYINT(display_width=1), autoincrement=False, nullable=False))
        batch_op.drop_column('foto_perfil')
        batch_op.drop_column('es_prestador')

    # ### end Alembic commands ###
