"""Inicial

Revision ID: 846231566141
Revises: 
Create Date: 2023-12-02 12:05:39.873268

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '846231566141'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('localidades',
    sa.Column('cod_postal', sa.Integer(),  nullable=False),
    sa.Column('nombre', sa.String(length=150), nullable=False),
    sa.Column('provincia', sa.String(length=150), nullable=False),
    sa.PrimaryKeyConstraint('cod_postal')
    )
    op.create_table('profesiones',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nombre', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('usuarios',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nombre', sa.String(length=40), nullable=False),
    sa.Column('apellido', sa.String(length=40), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('contrasenia', sa.String(length=250), nullable=False),
    sa.Column('fecha_nacimiento', sa.DateTime(), nullable=False),
    sa.Column('telefono', sa.String(length=20), nullable=False),
    sa.Column('esPrestador', sa.Boolean(), nullable=False),
    sa.Column('fotoPerfil', sa.String(length=255), nullable=True),
    sa.Column('foto', sa.LargeBinary(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('direcciones',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('calle', sa.String(length=45), nullable=False),
    sa.Column('numero', sa.String(length=10), nullable=False),
    sa.Column('piso', sa.String(length=10), nullable=True),
    sa.Column('dpto', sa.String(length=10), nullable=True),
    sa.Column('id_usuario', sa.Integer(), nullable=False),
    sa.Column('cod_postal', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['cod_postal'], ['localidades.cod_postal'], ),
    sa.ForeignKeyConstraint(['id_usuario'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('prestador_profesiones',
    sa.Column('id_prestador', sa.Integer(), nullable=False),
    sa.Column('id_profesion', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_prestador'], ['usuarios.id'], ),
    sa.ForeignKeyConstraint(['id_profesion'], ['profesiones.id'], ),
    sa.PrimaryKeyConstraint('id_prestador', 'id_profesion')
    )
    op.create_table('solicitudes',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('fechahora', sa.DateTime(), nullable=False),
    sa.Column('titulo', sa.String(length=45), nullable=False),
    sa.Column('descripcion', sa.String(length=255), nullable=False),
    sa.Column('estado', sa.String(length=20), nullable=False),
    sa.Column('id_direccion', sa.Integer(), nullable=False),
    sa.Column('id_profesion', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_profesion'], ['profesiones.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('fotos_solicitud',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('foto', sa.LargeBinary(), nullable=False),
    sa.Column('nombre', sa.String(length=50), nullable=False),
    sa.Column('tipo', sa.String(length=45), nullable=False),
    sa.Column('id_solicitud', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_solicitud'], ['solicitudes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('presupuestos',
    sa.Column('id_solicitud', sa.Integer(), nullable=False),
    sa.Column('id_prestador', sa.Integer(), nullable=False),
    sa.Column('materiales', sa.String(length=255), nullable=False),
    sa.ForeignKeyConstraint(['id_prestador'], ['usuarios.id'], ),
    sa.ForeignKeyConstraint(['id_solicitud'], ['solicitudes.id'], ),
    sa.PrimaryKeyConstraint('id_solicitud', 'id_prestador')
    )
    op.create_table('horarios_presupuesto',
    sa.Column('id_solicitud', sa.Integer(), nullable=False),
    sa.Column('id_prestador', sa.Integer(), nullable=False),
    sa.Column('horario', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['id_prestador', 'id_solicitud'], ['presupuestos.id_prestador', 'presupuestos.id_solicitud'], ),
    sa.PrimaryKeyConstraint('id_solicitud', 'id_prestador', 'horario')
    )
    op.create_table('servicios',
    sa.Column('id_solicitud', sa.Integer(), autoincrement=False, nullable=False),
    sa.Column('id_prestador', sa.Integer(), nullable=False),
    sa.Column('fechahora', sa.DateTime(), nullable=False),
    sa.Column('estado', sa.String(length=45), nullable=False),
    sa.Column('resenia', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['id_prestador', 'id_solicitud'], ['presupuestos.id_prestador', 'presupuestos.id_solicitud'], ),
    sa.PrimaryKeyConstraint('id_solicitud', 'id_prestador')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('servicios')
    op.drop_table('horarios_presupuesto')
    op.drop_table('presupuestos')
    op.drop_table('fotos_solicitud')
    op.drop_table('solicitudes')
    op.drop_table('prestador_profesiones')
    op.drop_table('direcciones')
    op.drop_table('usuarios')
    op.drop_table('profesiones')
    op.drop_table('localidades')
    # ### end Alembic commands ###
